name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy: 
      matrix: 
        node-version: [16.15.*]

    steps:
    - uses: actions/checkout@v3
    - name: Install packages 
      run: npm install
    - name: Build ts
      run: npm i -g @nestjs/cli && nest build
    - name: Pack the binaries
      run: npm install -g pkg@5.5.1 && pkg .
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag guradian-notify:$(date +%s)
